# 앱에 관한 기본 정보(현재버전, 종속 항목, 함께 제공될 애넷 지정)

# 프로젝트 이름
name: daenglog_fe
description: A new Flutter project.

# 퍼블리시 설정
publish_to: 'none' 

# 버전 설정
version: 0.0.1+1

# 환경 설정
environment:
  sdk: '>=2.19.4 <4.0.0'

# 의존성 추가
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.10 # 링크 열기 라이브러리
  http: ^0.13.5 # http 호출 라이브러리
  intl: ^0.19.0 # 국제화 라이브러리

  english_words: ^4.0.0 # 영어 단어 라이브러리
  provider: ^6.0.0 # 상태 관리 라이브러리

  image_picker: ^1.1.2 # 이미지 선택 라이브러리
  permission_handler: ^11.1.0 # 권한 관리 라이브러리

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # 린트 라이브러리

# 플러터 설정
flutter:
  uses-material-design: true # 머티리얼 디자인 사용 여부
  assets:
    # 로고
    - assets/images/home/daeng.png
    - assets/images/home/text.png
    
    # 스플래쉬
    - assets/images/splash/entire.png 
    
    
    # 소셜 로그인 아이콘
    - assets/images/login/login_logo.png
    - assets/images/login/naver_icon.png
    - assets/images/login/google_icon.png
    - assets/images/login/kakao_icon.png
    - assets/images/login/apple_icon.png
    
    # 온보딩 이미지
    - assets/images/onboding/onboding.png
    - assets/images/onboding/onboding_first.png
    - assets/images/onboding/onboding_sec.png
    - assets/images/onboding/onboding_trd.png
    - assets/images/onboding/onboding_fth.png
    
    # 서비스 수집 배경 이미지
    - assets/images/information/info_background.png
  
  # 폰트
  fonts:
    # 폰트 프리텐다드
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf