# 앱에 관한 기본 정보(현재버전, 종속 항목, 함께 제공될 애넷 지정)

# 프로젝트 이름
name: daenglog_fe
description: A new Flutter project.

# 퍼블리시 설정
publish_to: 'none' 

# 버전 설정
version: 0.0.1+1

# 환경 설정
environment:
  sdk: '>=2.19.4 <4.0.0'

# 의존성 추가
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.10 # 링크 열기 라이브러리
  http: ^0.13.5 # http 호출 라이브러리
  intl: ^0.19.0 # 국제화 라이브러리
  dio: ^5.8.0+1 # dio 라이브러리
  retrofit: ^4.0.0 # retrofit 라이브러리
  json_annotation: ^4.9.0 # json 라이브러리
  build_runner: ^2.4.12 # build_runner 라이브러리
  json_serializable: ^6.9.3 # json_serializable 라이브러리

  english_words: ^4.0.0 # 영어 단어 라이브러리
  provider: ^6.0.0 # 상태 관리 라이브러리

  image_picker: ^1.1.2 # 이미지 선택 라이브러리
  permission_handler: ^11.1.0 # 권한 관리 라이브러리

  flutter_lints: ^2.0.0 # 린트 라이브러리

  shared_preferences: ^2.3.5 # 공유 프레퍼런스 라이브러리
  
  flutter_secure_storage: ^9.2.2 # 보안 저장소 라이브러리

  share_plus: ^7.2.1 # 공유 기능 라이브러리
  path_provider: ^2.1.2 # 파일 경로 관리 라이브러리
  image_gallery_saver: ^2.0.3 # 갤러리 저장 라이브러리
  lottie: ^3.0.0 # Lottie 애니메이션 라이브러리

  geolocator: ^11.0.0 # 위치 정보 라이브러리
  geocoding: ^2.1.0 # 위치 정보 라이브러리
  flutter_dotenv: ^5.2.1 # 환경 변수 라이브러리
  flutter_colorpicker: ^1.0.3 # 색상 선택 라이브러리 
  go_router: ^14.2.0 # 라우터 라이브러리

  google_sign_in: ^6.2.0 # 구글 로그인 라이브러리

# 플러터 설정
flutter:
  uses-material-design: true # 머티리얼 디자인 사용 여부
  assets:
    - .env

    # 메인
    - assets/images/home/daeng.jpg
    - assets/images/home/daeng.png
    - assets/images/home/text.png
    - assets/images/home/home_icon.png
    - assets/images/home/market_icon.png
    - assets/images/home/mypage_icon.png
    - assets/images/home/record_icon.png
    - assets/images/home/camera_icon.png
    - assets/images/home/mango_image.png
    - assets/images/home/rain.png
    - assets/images/home/sun.png
    - assets/images/home/snow.png
    - assets/images/home/default_profile.png


    # 메인 위젯 사진
    - assets/images/home/widget/dog_icon.png
    - assets/images/home/widget/plus_icon.png
    - assets/images/home/widget/Goal_icon.png
    - assets/images/home/widget/Sun_icon.png
    - assets/images/home/widget/Journal_icon.png
    
    # 날씨 이미지
    - assets/images/weather/walking_dog.png
    
    # 스플래쉬
    - assets/images/splash/entire.png 
    
    
    # 소셜 로그인 아이콘
    - assets/images/login/login_logo.png
    - assets/images/login/naver_icon.png
    - assets/images/login/google_icon.png
    - assets/images/login/kakao_icon.png
    - assets/images/login/apple_icon.png
    
    # 온보딩 이미지
    - assets/images/onboding/onboding.png
    - assets/images/onboding/onboding_first.png
    - assets/images/onboding/onboding_sec.png
    - assets/images/onboding/onboding_trd.png
    - assets/images/onboding/onboding_fth.png
    
    # 서비스 수집 배경 이미지
    - assets/images/information/info_background.png
    - assets/images/information/camera.png

    # 채팅 화면 아이콘
    - assets/images/chat/download_icon.png
    - assets/images/chat/send_icon.png

    # 가족 공유 화면 아이콘
    - assets/images/family/envelope.png

    # 가족 공유 화면 애니메이션
    - assets/images/family/send.json
    - assets/images/family/send_back.jpg

    # 테스트 이미지
    - assets/images/test.png

  # 폰트
  fonts:
    # 폰트 프리텐다드
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900

    # 폰트 영덕 눈사람
    - family: Yeongdeok-Snow-Crab
      fonts:
        - asset: assets/fonts/yeongdeok/Yeongdeok-Snow-Crab.ttf
    # 폰트 영덕 바다
    - family: Yeongdeok-Sea
      fonts:
        - asset: assets/fonts/yeongdeok/Yeongdeok-Sea.ttf
    # 폰트 수트
    - family: Suite-Regular
      fonts:
        - asset: assets/fonts/suite/SUITE-Regular.ttf
    - family: Suite-Medium
      fonts:
        - asset: assets/fonts/suite/SUITE-Medium.ttf
    - family: Suite-Bold
      fonts:
        - asset: assets/fonts/suite/SUITE-Bold.ttf
    - family: Suite-ExtraBold
      fonts:
        - asset: assets/fonts/suite/SUITE-ExtraBold.ttf
    - family: Suite-SemiBold
      fonts:
        - asset: assets/fonts/suite/SUITE-SemiBold.ttf